apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mongo-operator-cluster-role
  namespace: default
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "create"]
- apiGroups: ["operators.ultimaker.com"]
  resources: ["mongos"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["secrets", "services"]
  verbs: ["get", "create"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "create"]
