apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongo-operator
  name: mongo-operator
  namespace: ultimaker
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mongo-operator
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo-operator
    spec:
      containers:
        image: ultimaker/mongo-operator:latest
        imagePullPolicy: IfNotPresent
        name: mongo-operator
