apiVersion: "operators.ultimaker.com/v1"
kind: Mongo
metadata:
  name: mongo-cluster
  namespace: default
spec:
  mongodb:
    replicas: 3  # Must be between 3 and 50
    cpu_limit: "100m"
    memory_limit: "64Mi"
  backups:
    cron: "0 * * * *"  # every hour at 0 minutes
    gcs:
      bucket: "ultimaker-mongo-backups"
      prefix: "backups"
      serviceAccount:
        secretKeyRef:
          key: json
          name: storage-serviceaccount
