apiVersion: "operators.ultimaker.com/v1"
kind: Mongo
metadata:
  name: some-db
  namespace: mongo-ns
spec:
  mongodb:
    replicas: 3  # Must be an odd number of minimum 3.
    cpu_limit: "100m"
    memory_limit: "64Mi"
  backups:
    gcs:
      bucket: "mongo-backups"
      serviceaccount:
        valueFrom:
          secretKeyRef:
            key: json
            name: storage-serviceaccount
